#!/bin/bash
# Easy script to create docker

NAME=$1
REPO=$2
PORT=$3
BRANCH=$(git rev-parse --abbrev-ref HEAD)

if [[ $# -ne 3 ]]; then
  echo "Not enough parameters"
  echo "Usage: "
  echo "       dockerize <:name> <:repo> <:port>"
  exit 1
fi

echo "Creating container $NAME from $REPO/$BRANCH exposing :$PORT"

docker run -d \
  --name=$1 \
  --restart=always \
  -e repo=$REPO \
  -p $PORT:8080 \
  -e branch=$BRANCH \
  jordond/basesite